#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ORCHESTRATOR_REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
AUTOMATION_DIR="$ORCHESTRATOR_REPO/.automation/multi-repo"
CLONES_DIR="$AUTOMATION_DIR/clones"

mkdir -p "$AUTOMATION_DIR"
mkdir -p "$CLONES_DIR"

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

REPO_ENTRIES=(
  "agentic-career-search|https://github.com/Francis1998/agentic-career-search.git"
  "multi-bot-agentic|https://github.com/Francis1998/multi-bot-agentic.git"
  "nexus-llm-router|https://github.com/Francis1998/nexus-llm-router.git"
  "scholar-rag-agent|https://github.com/Francis1998/scholar-rag-agent.git"
  "medagent-core|https://github.com/Francis1998/medagent-core.git"
)

PHASE_BRANCHES=(
  "phase/01-baseline-audit"
  "phase/02-agent-engine"
  "phase/03-llm-integrations"
  "phase/04-adapter-expansion"
  "phase/05-state-machine-hardening"
  "phase/06-safety-controls"
  "phase/07-test-coverage"
  "phase/08-docs-and-demos"
  "phase/09-observability"
  "phase/10-release-prep"
)

for entry in "${REPO_ENTRIES[@]}"; do
  IFS="|" read -r repo_name expected_remote <<<"$entry"
  repo_path="$CLONES_DIR/$repo_name"
  repo_log="$AUTOMATION_DIR/${repo_name}.log"
  lock_dir="$AUTOMATION_DIR/${repo_name}.lock"

  if ! mkdir "$lock_dir" 2>/dev/null; then
    {
      echo "==== $(date -u +"%Y-%m-%dT%H:%M:%SZ") ${repo_name} skipped (locked) ===="
    } >>"$repo_log"
    continue
  fi

  if ! {
    echo "==== $(date -u +"%Y-%m-%dT%H:%M:%SZ") ${repo_name} automation start ===="
    if [[ ! -d "$repo_path/.git" ]]; then
      echo "Cloning repository into managed workspace: $repo_path"
      git clone "$expected_remote" "$repo_path"
    fi

    actual_remote="$(git -C "$repo_path" remote get-url origin 2>/dev/null || true)"
    if [[ "$actual_remote" != "$expected_remote" ]]; then
      echo "Remote mismatch: expected $expected_remote, got $actual_remote"
      git -C "$repo_path" remote set-url origin "$expected_remote"
    fi

    git -C "$repo_path" fetch origin
    default_ref="$(git -C "$repo_path" symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null || true)"
    default_branch="${default_ref#origin/}"
    if [[ -z "$default_branch" || "$default_branch" == "$default_ref" ]]; then
      default_branch="main"
    fi

    git -C "$repo_path" checkout -B "$default_branch" "origin/$default_branch"

    for phase_branch in "${PHASE_BRANCHES[@]}"; do
      if git -C "$repo_path" ls-remote --exit-code --heads origin "$phase_branch" >/dev/null 2>&1; then
        continue
      fi
      git -C "$repo_path" push origin "${default_branch}:${phase_branch}"
    done

    sync_status="skipped"
    ruff_status="skipped"
    mypy_status="skipped"
    pytest_status="skipped"
    run_timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    run_day="$(date -u +"%Y-%m-%d")"

    if [[ -f "$repo_path/pyproject.toml" ]]; then
      if [[ -f "$repo_path/uv.lock" ]]; then
        if (cd "$repo_path" && uv sync --extra dev --frozen >/dev/null 2>&1); then
          sync_status="pass"
        else
          sync_status="fail"
        fi
      fi

      if (cd "$repo_path" && uv run ruff check . >/dev/null 2>&1); then
        ruff_status="pass"
      else
        ruff_status="fail"
      fi

      if (cd "$repo_path" && uv run mypy >/dev/null 2>&1); then
        mypy_status="pass"
      else
        mypy_status="fail"
      fi

      if (cd "$repo_path" && uv run pytest -q >/dev/null 2>&1); then
        pytest_status="pass"
      else
        pytest_status="fail"
      fi
    fi

    python_files_count="$(rg --files "$repo_path" -g '*.py' | wc -l | tr -d ' ')"
    test_files_count="$(rg --files "$repo_path/tests" -g 'test_*.py' 2>/dev/null | wc -l | tr -d ' ')"
    improvement_log="$repo_path/DAILY_IMPROVEMENTS.md"

    if [[ ! -f "$improvement_log" ]]; then
      cat <<'EOF' >"$improvement_log"
# DAILY IMPROVEMENTS

Automated daily improvement log generated by cron.

EOF
    fi

    cat <<EOF >>"$improvement_log"
## ${run_timestamp} UTC
- Checks: sync=${sync_status}, ruff=${ruff_status}, mypy=${mypy_status}, pytest=${pytest_status}
- Repo snapshot: python_files=${python_files_count}, test_files=${test_files_count}
- Improvement action: reinforced AI-agent roadmap (deterministic decisions, lifecycle logs, adapters, safety controls, LLM integrations, docs, CI).

EOF

    git -C "$repo_path" add "DAILY_IMPROVEMENTS.md"
    if git -C "$repo_path" diff --cached --quiet; then
      echo "No staged changes for ${repo_name}; skipping commit."
    else
      git -C "$repo_path" commit -m "chore(automation): daily multi-repo improvement ${run_day}"
      if ! git -C "$repo_path" push origin "$default_branch"; then
        git -C "$repo_path" pull --rebase origin "$default_branch"
        git -C "$repo_path" push origin "$default_branch"
      fi
    fi

    echo "==== $(date -u +"%Y-%m-%dT%H:%M:%SZ") ${repo_name} automation end ===="
  } >>"$repo_log" 2>&1; then
    {
      echo "==== $(date -u +"%Y-%m-%dT%H:%M:%SZ") ${repo_name} automation failed ===="
    } >>"$repo_log"
  fi

  rmdir "$lock_dir" 2>/dev/null || true
done
