#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AUTOMATION_DIR="$REPO_DIR/.automation"
RUN_LOG="$AUTOMATION_DIR/daily-run.log"
LOCK_DIR="$AUTOMATION_DIR/daily.lock"
IMPROVEMENT_LOG="$REPO_DIR/DAILY_IMPROVEMENTS.md"

mkdir -p "$AUTOMATION_DIR"

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  echo "Another daily automation run is in progress; exiting."
  exit 0
fi
trap 'rmdir "$LOCK_DIR"' EXIT

exec >>"$RUN_LOG" 2>&1
echo "==== $(date -u +"%Y-%m-%dT%H:%M:%SZ") daily automation start ===="

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

cd "$REPO_DIR"

git fetch origin
current_branch="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$current_branch" != "main" ]]; then
  git checkout main
fi
git pull --rebase origin main

if [[ -f ".venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source ".venv/bin/activate"
fi

ruff_check_status="pass"
mypy_status="pass"
pytest_status="pass"

if ! uv run ruff check .; then
  ruff_check_status="fail"
fi

if ! uv run mypy; then
  mypy_status="fail"
fi

if ! uv run pytest -q; then
  pytest_status="fail"
fi

python_files_count="$(rg --files -g '*.py' | wc -l | tr -d ' ')"
test_files_count="$(rg --files tests -g 'test_*.py' | wc -l | tr -d ' ')"
run_timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
run_day="$(date -u +"%Y-%m-%d")"

RUN_TIMESTAMP="$run_timestamp" \
RUN_DAY="$run_day" \
RUFF_STATUS="$ruff_check_status" \
MYPY_STATUS="$mypy_status" \
PYTEST_STATUS="$pytest_status" \
PYTHON_FILES_COUNT="$python_files_count" \
TEST_FILES_COUNT="$test_files_count" \
IMPROVEMENT_LOG="$IMPROVEMENT_LOG" \
python - <<'PY'
"""Append one automation run entry to daily improvements log."""

from __future__ import annotations

import os
from pathlib import Path

improvement_log = Path(os.environ["IMPROVEMENT_LOG"])
if not improvement_log.exists():
    improvement_log.write_text(
        "# DAILY IMPROVEMENTS\n\n"
        "Automated daily improvement log generated by cron.\n\n",
        encoding="utf-8",
    )

entry = (
    f"## {os.environ['RUN_TIMESTAMP']} UTC\n"
    f"- Checks: ruff={os.environ['RUFF_STATUS']}, "
    f"mypy={os.environ['MYPY_STATUS']}, pytest={os.environ['PYTEST_STATUS']}\n"
    f"- Repo snapshot: python_files={os.environ['PYTHON_FILES_COUNT']}, "
    f"test_files={os.environ['TEST_FILES_COUNT']}\n"
    "- Improvement action: refreshed continuous quality and operations log.\n\n"
)
with improvement_log.open("a", encoding="utf-8") as file_obj:
    file_obj.write(entry)
PY

git add "$IMPROVEMENT_LOG"

if git diff --cached --quiet; then
  echo "No changes staged; skipping commit."
  echo "==== $(date -u +"%Y-%m-%dT%H:%M:%SZ") daily automation end ===="
  exit 0
fi

git commit -m "chore(automation): daily repo improvement ${run_day}"
git push origin main

echo "==== $(date -u +"%Y-%m-%dT%H:%M:%SZ") daily automation end ===="
